### ISSUE TITLE
advice for installing on Cent OS 6.10?

### ISSUE THREAD

**Issue by markosjal** [google/oauth2l#41]
Any advice for installing in centos 6.10?

pip install google-oauth2l
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/setuptools-40.0.0-py2.6.egg/pkg_resources/__init__.py", line 72, in <module>
    from . import py31compat
  File "/usr/lib/python2.6/site-packages/setuptools-40.0.0-py2.6.egg/pkg_resources/py31compat.py", line 18, in <module>
    sys.version_info.major == 2 or
AttributeError: 'tuple' object has no attribute 'major'

**Comment by wora** [comment]
The Go version will be ready soon. Please use that version instead. The Python version depends on a deprecated library, which is too costly to replace it.
